-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTReUh7A215Y3m6n4
ko2pl2eKVsNTlpujMrTr2aOr3NygCgYIKoZIzj0DAQehRANCAATaIkB2mRCdmSEg
8LL/aLcZotlQhiIrtEUjjGB3AhUHGlwHEWeZjpbcPdezaMum/ZNKe1+8JCS3IAlg
RJf3uCp2
-----END PRIVATE KEY-----